### ISSUE TITLE
Foto in vandaag menu

### ISSUE THREAD

**Issue by JustJoxem** [Argo-Client/App#2]
Als ik mijn foto uitzet in de instellingen staat hij nogsteeds boven aan de vandaag pagina

**Comment by Netfloex** [comment]
Dat is inderdaad niet helemaal de bedoeling, we zetten het erbij:
https://github.com/orgs/Argo-Client/projects/1

**Comment by Netfloex** [comment]
Dit is nu opgelost:
https://github.com/Argo-Client/App/commit/077fefd5646399ad47b0b55af652a04be9d1ea84
