### ISSUE TITLE
toggleHuiswerk overschijft Magister aantekening

### ISSUE THREAD

**Issue by HarryDeKat** [Argo-Client/App#8]
## Wat gaat er mis?
```
var res = await api.dio.put(
   "api/personen/${account.id}/afspraken/${les.id}",
   data: json.encode({"Id": les.id, "Afgerond": !les.huiswerkAf}),
);
```
De toggleHuiswerk functie stuurt het bovenstaande stuk code als data, maar doordat Magister's API op een erg interessante manier werkt, overschrijft hij dan alles wat niet in de gestuurde data zat naar `null`. Ik heb dit gemerkt toen ik wat data in Magister's aantekeningen zette, maar ik heb geen idee of er nog andere dingen zijn die worden overschreven.
## Mogelijke oplossing
Dit is volgens mij op te lossen door de toggleHuiswerk functie te herschrijven naar het onderstaande stuk code.
```
les.huiswerkAf = !les.huiswerkAf
var res = await api.dio.put(
   "api/personen/${account.id}/afspraken/${les.id}",
   data: json.encode(les),
);
```

**Comment by Netfloex** [comment]
Aha goed gevonden, dat kan wel kloppen inderdaad want kan me vaag herinneren dat Magister zelf inderdaad alles stuurt. Zelf hebben we geen Magister meer, dus wil je misschien een PR maken?
Dit is trouwens wel iets lastiger omdat hoe Argo lessen opslaat heel anders is dan Magister, dat betekent dat je suggestie niet helemaal klopt en net iets moeilijker word.

**Comment by HarryDeKat** [comment]
Ik zag inderdaad dat het wat lastiger was dan dat ik mij had voorgesteld, maar aangezien er volgens mij niets anders is wat overschreven kan worden is het ook mogelijk om het te veranderen naar
```
      var res = await api.dio.put(
        "api/personen/${account.id}/afspraken/${les.id}",
        data: json.encode({"Id": les.id, "Afgerond": !les.huiswerkAf, "Aantekening": les.aantekening}),
      );
```
